#!/usr/bin/env php
<?php

use Core\Model;
use Core\TwitterApi;
use Model\Unfollower;

/** @var TwitterApi $api */
$api = include __DIR__ . '/../bootstrap.php';

$followers    = Model::getList('followers');
$friends      = Model::getList('friends');
$whitelist    = Model::getList('whitelist');
$nowDate      = (new \DateTime())->format('Y-m-d');
$expiredDate  = (new \DateTime())->modify('-' . DEFAULT_UNFOLLOW_DAYS . ' days')->format('Y-m-d');

$destroyUsers = array_diff_key($friends, $followers, $whitelist);
$destroyTotal = count($destroyUsers);
$destroyCount = 0;

if ($destroyUsers) {

    $unfollowers = Unfollower::load();

    foreach ($destroyUsers as $id => $destroyUser) {

        if (!array_key_exists('_' . $id, $friends)) {

            continue;
        }

        $friend = $friends['_' . $id];

        if ('' === (string) $friend['date']
            || (new \DateTime($friend['date']))->format('Y-m-d') < $expiredDate) {

            $friend['date'] = $nowDate;

            Unfollower::sync($friend);

            // Unfollow
//            $api->post('friendships/destroy', [
//                'user_id' => $destroyUser['id'],
//            ]);
//            sleep(1);

            echo $destroyUser['screen_name'] . "\n";
            $destroyCount++;
        }
    }

    Unfollower::save();
}

echo $destroyCount . " / " . $destroyTotal . " users\n";
echo "------------------------------\n";
